# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_nodes/CUSTOM.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class CUSTOM(genpy.Message):
  _md5sum = "72b7d00343e79c9d46317e89cc776a54"
  _type = "robot_nodes/CUSTOM"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Adding custom data here

#Adding a string
std_msgs/String str_var1

#Adding a custom int variable
std_msgs/Int32 int_var1

#Custom bool variable
std_msgs/Bool bool_var1

#Variable-length-vector of ints
#std_msgs/RegionOfInterest[] ints_list





================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/Int32
int32 data
================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['str_var1','int_var1','bool_var1']
  _slot_types = ['std_msgs/String','std_msgs/Int32','std_msgs/Bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       str_var1,int_var1,bool_var1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CUSTOM, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.str_var1 is None:
        self.str_var1 = std_msgs.msg.String()
      if self.int_var1 is None:
        self.int_var1 = std_msgs.msg.Int32()
      if self.bool_var1 is None:
        self.bool_var1 = std_msgs.msg.Bool()
    else:
      self.str_var1 = std_msgs.msg.String()
      self.int_var1 = std_msgs.msg.Int32()
      self.bool_var1 = std_msgs.msg.Bool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.str_var1.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_iB.pack(_x.int_var1.data, _x.bool_var1.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.str_var1 is None:
        self.str_var1 = std_msgs.msg.String()
      if self.int_var1 is None:
        self.int_var1 = std_msgs.msg.Int32()
      if self.bool_var1 is None:
        self.bool_var1 = std_msgs.msg.Bool()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.str_var1.data = str[start:end].decode('utf-8')
      else:
        self.str_var1.data = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.int_var1.data, _x.bool_var1.data,) = _struct_iB.unpack(str[start:end])
      self.bool_var1.data = bool(self.bool_var1.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.str_var1.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_iB.pack(_x.int_var1.data, _x.bool_var1.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.str_var1 is None:
        self.str_var1 = std_msgs.msg.String()
      if self.int_var1 is None:
        self.int_var1 = std_msgs.msg.Int32()
      if self.bool_var1 is None:
        self.bool_var1 = std_msgs.msg.Bool()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.str_var1.data = str[start:end].decode('utf-8')
      else:
        self.str_var1.data = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.int_var1.data, _x.bool_var1.data,) = _struct_iB.unpack(str[start:end])
      self.bool_var1.data = bool(self.bool_var1.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_iB = struct.Struct("<iB")
